// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// The runtime Prisma Client gets its connection from the pg adapter in
// src/lib/prisma.ts. The url below is only consumed by the Prisma CLI
// (migrate, db pull, db push), which requires the DIRECT Neon endpoint:
// the pooled (-pooler) endpoint is PgBouncer transaction mode and does not
// support schema operations. DIRECT_URL is the same host minus "-pooler".
const directUrl =
  process.env["DIRECT_URL"] ??
  (process.env["DATABASE_URL"] ?? "").replace("-pooler", "");

// pg warns for sslmode=prefer|require|verify-ca (aliases of verify-full) —
// normalize so the deprecation warning never prints during CLI runs.
const safeDirectUrl = directUrl.replace(/sslmode=(prefer|require|verify-ca)(?=&|$)/gi, "sslmode=verify-full");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Marketplace demo seed — `prisma db seed` (see prisma/seed.js).
    seed: "node prisma/seed.js",
  },
  datasource: {
    url: safeDirectUrl,
  },
});
