import { describe, it, expect, beforeAll } from "@jest/globals";
import { spawnSync } from "child_process";

/**
 * Regression guard: the GitHub contributor graph is derived from the author
 * name/email of every commit reachable from the default branch. This test
 * asserts that history contains ONLY the repo owner's identity — no AI-agent
 * accounts (wonivaj516, Codebuff, devin-ai-integration, freebuff, etc.) may
 * ever appear as author or committer, and no AI-tooling footers may be baked
 * into commit messages.
 *
 * Deterministic and offline: it reads local git history, so it does not need
 * network access or a GitHub token in CI.
 */

const OWNER_NAMES = new Set(["Sumit", "sumitagg24"]);
const OWNER_EMAIL = "sumitagg24@gmail.com";

// Substrings that must never appear anywhere in the author/committer line.
const FORBIDDEN_IDENTITIES = ["wonivaj516", "codebuff", "devin", "freebuff"];

// Footers/credits that must never appear in any commit message body.
const FORBIDDEN_FOOTERS = [
  "Co-Authored-By:",
  "Generated with Codebuff",
  "Generated by Devin",
  "Devin AI",
];

let authors: string[];
let committers: string[];
let messages: string;

function gitLog(args: string[]): string {
  const res = spawnSync("git", ["log", ...args], { encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
  if (res.status !== 0) {
    throw new Error(`git log failed: ${res.stderr || res.error?.message || "unknown error"}`);
  }
  return res.stdout.trim();
}

beforeAll(() => {
  authors = gitLog(["--format=%an <%ae>"]).split("\n").filter(Boolean);
  committers = gitLog(["--format=%cn <%ce>"]).split("\n").filter(Boolean);
  messages = gitLog(["--format=%B"]);
});

describe("git contributor hygiene", () => {
  it("has commit history at all (sanity: git repo present)", () => {
    expect(authors.length).toBeGreaterThan(0);
  });

  it("every author is the repo owner (sumitagg24@gmail.com)", () => {
    const offenders = [...new Set(authors)].filter((line) => {
      const [name, email] = splitIdentity(line);
      return name === undefined || email !== OWNER_EMAIL || !OWNER_NAMES.has(name);
    });
    expect(offenders).toEqual([]);
  });

  it("every committer is the repo owner (sumitagg24@gmail.com)", () => {
    const offenders = [...new Set(committers)].filter((line) => {
      const [name, email] = splitIdentity(line);
      return name === undefined || email !== OWNER_EMAIL || !OWNER_NAMES.has(name);
    });
    expect(offenders).toEqual([]);
  });

  it("no AI-agent identity appears in author/committer lines", () => {
    const all = [...new Set([...authors, ...committers])].join("\n").toLowerCase();
    const hits = FORBIDDEN_IDENTITIES.filter((id) => all.includes(id));
    expect(hits).toEqual([]);
  });

  it("no AI-tooling footer is baked into any commit message", () => {
    const lower = messages.toLowerCase();
    const hits = FORBIDDEN_FOOTERS.filter((footer) => lower.includes(footer.toLowerCase()));
    expect(hits).toEqual([]);
  });
});

function splitIdentity(line: string): [string | undefined, string | undefined] {
  const match = /^(.+) <(.+)>$/.exec(line);
  return match ? [match[1], match[2]] : [undefined, undefined];
}
